name: Docker

on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Docker Buildx and publish
        uses: ilteoood/docker_buildx@master
        with:
          imageName: rsaikali/dht22-mqtt
          platform: linux/arm/v7
          dockerHubUser: ${{ secrets.DOCKER_HUB_LOGIN }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
          publish: true
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: rsaikali/dht22-mqtt

