name: buildx

on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        run: |
          docker buildx create --use --name armbuild --node build --driver-opt network=host
      -
        name: Run Buildx
        run: |
          docker buildx armbuild --platform linux/arm/v7 -t rsaikali/dht22-mqtt .
