name: buildx

on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      - name: Docker multi-arch buildx
        uses: ilteoood/docker_buildx@v1.0.1
        with:
          imageName: rsaikali/dht22-mqtt
          publish: true
          platform: linux/arm/v7
          dockerHubUser: ${{ secrets.DOCKER_HUB_LOGIN }}
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
